[WIP] Basic Nonce handling
MyCryptoHQ/signer pull request #107
Opened 2021-05-06 13:32 UTC by FrederikBolding

2021-05-06 13:34 UTC, FrederikBolding commented
[ch8379]

2021-05-07 13:04 UTC, Mrtenz requested changes

2021-05-07 13:04 UTC, Mrtenz commented on src/app/screens/Transaction.tsx
> +  })();
Can this be moved to a selector or separate function?

2021-05-07 14:13 UTC, Mrtenz requested changes

2021-05-07 14:53 UTC, Mrtenz approved these changes

2021-05-07 14:56 UTC, merged