[WIP] General Storage
MyCryptoHQ/signer pull request #18
Opened 2020-10-05 14:36 UTC by FrederikBolding

2020-10-05 16:38 UTC, FrederikBolding commented
[ch6995]

2020-10-06 14:07 UTC, Mrtenz requested changes

2020-10-06 14:07 UTC, Mrtenz commented on src/app/screens/NewUser.tsx
> +      <label htmlFor="password">
You don't need a `htmlFor` property if the input is inside the label.

2020-10-06 14:07 UTC, Mrtenz commented on src/app/screens/NewUser.tsx
> +          onChange={(e) => setPassword(e.currentTarget.value)}
Don't use arrow functions inside properties, they cause unnecessary re-renders.

https://stackoverflow.com/a/36677798/11285318

2020-10-06 14:07 UTC, Mrtenz commented on src/app/screens/Login.tsx
> +    }
Maybe handle Promise rejections here as well.

2020-10-06 14:07 UTC, Mrtenz commented on src/app/screens/NewUser.tsx
> +    }
Maybe handle Promise rejections here as well.

2020-10-06 14:12 UTC, FrederikBolding commented on src/api/db.ts
> +export const testables = { handleRequest };
I just wanted to export it for testing, but didn't want it easily accessible from the outside.

2020-10-06 14:36 UTC, FrederikBolding commented on src/types/db.ts
> +  NEW_USER,
I get that. We can use two booleans instead, but if the user has never set up the app, telling whether they're `loggedIn` is meaningless. That's why I felt that using an enum to represent the 3 states was better.

2020-10-06 14:36 UTC, FrederikBolding commented on src/api/db.ts
> +let store: Store;
Instead of using `electron-store`?

2020-10-06 15:05 UTC, Mrtenz commented on src/api/db.ts
> +let store: Store;
We can still use `electron-store` (for persisting), but I think a Redux store in between is more scalable.

2020-10-06 15:05 UTC, Mrtenz commented on src/api/db.ts
> +export const testables = { handleRequest };
I would personally just export the function. It's a private API regardless, so there's no significant difference.

2020-10-06 16:05 UTC, Mrtenz approved these changes

2020-10-06 16:06 UTC, merged