[WIP] Top Navigation
MyCryptoHQ/signer pull request #49
Opened 2021-03-03 14:47 UTC by FrederikBolding

2021-03-03 14:47 UTC, FrederikBolding commented
[ch8258]

2021-03-04 13:45 UTC, GuillaumeRx requested changes

2021-03-04 13:45 UTC, GuillaumeRx commented on src/app/components/Core/Box.tsx
> +export default Box;
I don't think we need this one since rebass has his own `Box` and `Flex` components

2021-03-04 13:45 UTC, GuillaumeRx commented on src/app/components/Core/LinkApp.tsx
> +const SLink = styled('a')<LinkStyleProps & React.AnchorHTMLAttributes<HTMLAnchorElement>>`
We should convert to the Rebass `Link` and get rid of the style-component/styled-system method

2021-03-04 13:45 UTC, GuillaumeRx commented on src/app/theme/theme.ts
> +});
Migrate those variant to the theme, with rebass it's easier to ship them with the theme (https://rebassjs.org/variants)

2021-03-04 16:13 UTC, GuillaumeRx approved these changes

2021-03-04 16:14 UTC, merged