[WIP] Account Management
MyCryptoHQ/signer pull request #75
Opened 2021-04-05 11:09 UTC by FrederikBolding

2021-04-05 11:09 UTC, FrederikBolding commented
[ch8438]

2021-04-05 14:14 UTC, Mrtenz requested changes
Few things regarding the design:
- I think there should be slightly more padding between the blocky/delete icon and address
- The blockie should be top aligned
- The font size is too big for the address
- The delete overlay should span the entire width

2021-04-05 14:14 UTC, Mrtenz commented on src/app/components/EditableText.tsx
> +          onChange={(e) => setEditValue(e.currentTarget.value)}
Don´t use an arrow function here

2021-04-05 14:14 UTC, Mrtenz commented on src/app/components/EditableText.tsx
> +        <Input
This input is being changed from uncontrolled to controlled when writing something in it. I´m not sure why, but this should be avoided if possible.

2021-04-06 12:22 UTC, Mrtenz approved these changes

2021-04-06 12:22 UTC, merged