Refactor WebSocket handler to use Redux
MyCryptoHQ/signer pull request #90
Opened 2021-04-21 15:23 UTC by Mrtenz

2021-04-21 16:08 UTC, Mrtenz commented
[ch8498]

2021-04-21 19:38 UTC, Mrtenz commented
[ch8528]

2021-04-22 09:14 UTC, FrederikBolding requested changes

2021-04-22 09:14 UTC, FrederikBolding commented on src/utils/validators.ts
> +export const isValidParams = (request: JsonRPCRequest, method: JsonRPCMethod) => {
Couldn't we just use the method from the request itself?

2021-04-22 09:14 UTC, FrederikBolding commented on src/types/jsonrpc.ts
> +export interface JsonRPCResponse<Result = unknown, Error = unknown> {
Should we do a union type for this to separate when `result` and `error` are present?

2021-04-22 09:14 UTC, FrederikBolding commented on src/api/store/ws.sagas.test.ts
> +      .dispatch(reply({ id: 2, result: 'foo' }))
Please change `result` to something else just to be safe.

2021-04-22 09:14 UTC, FrederikBolding commented on src/api/store/ws.sagas.test.ts
> +  it('handles socket requests', async () => {
Can we add some comments to explain this test?

2021-04-22 09:14 UTC, FrederikBolding commented on src/api/store/ws.sagas.test.ts
> +      origin: fRequestOrigin
If this is the header, then `fRequestOrigin` is not a valid one. Since it doesn't include `https://` etc.

2021-04-22 09:14 UTC, FrederikBolding commented on src/api/store/accounts.sagas.test.ts
> +    await expectSaga(getAccountsWorker, requestAccounts({ origin: 'app.mycrypto.com', request }))
Use `fRequestOrigin`

2021-04-22 09:27 UTC, Mrtenz commented on src/api/store/ws.sagas.ts
> +    yield fork(handleRequest, payload);
Multiple websocket messages can come in at the same time, and we don't want one message to block all other messages.

2021-04-22 09:28 UTC, Mrtenz commented on src/api/store/ws.sagas.test.ts
> +jest.mock('electron');
Yeah, since it indirectly imports from `@api/db`.

2021-04-22 11:40 UTC, FrederikBolding approved these changes

2021-04-22 11:41 UTC, merged