Remove unused bridge code
MyCryptoHQ/signer pull request #91
Opened 2021-04-21 16:08 UTC by Mrtenz

Needs to be rebased once #90 is merged.

2021-04-21 16:09 UTC, Mrtenz commented
[ch8498]

2021-04-23 08:19 UTC, FrederikBolding requested changes

2021-04-23 08:19 UTC, FrederikBolding commented on src/app/screens/__tests__/AddAccount.test.tsx
> -  it('can submit mnemonic from another DPath and page', async () => {
I would prefer if we could keep this test. Would it be possible to run it with a regular store to fix the problems you've had?

2021-04-23 08:19 UTC, FrederikBolding commented on src/app/screens/AddAccount/AddAccountMnemonic.tsx
> +    dispatch(setAddresses([]));
Is this needed? Doesn't fetch addresses overwrite?

2021-04-23 08:19 UTC, FrederikBolding commented on src/bridge.spec.ts
> +    it('listens to an event', () => {
Perhaps add the unsubscribe test as part of the text?

2021-04-23 12:25 UTC, FrederikBolding approved these changes

2021-04-23 12:30 UTC, merged